### ISSUE TITLE
在发送合并转发消息时，出现error的问题

### ISSUE THREAD

**Issue by ycvk** [2mf8/go-pbbot-for-rq#1]
https://github.com/2mf8/GoneBot/blob/2176fea2af8ac992663165f5750fcf1845168813/bot.go#L459-L460

因为对接的 lagrange 的这个接口返回值字段为`resid` [lagrange文档](https://lagrangedev.github.io/Lagrange.Doc/Lagrange.OneBot/API/Extend/#%E6%9E%84%E9%80%A0%E5%90%88%E5%B9%B6%E8%BD%AC%E5%8F%91%E6%B6%88%E6%81%AF)

所以`sfm.Data`会出现`nil.Data`的空指针问题

我不知此项目是否全适配 Lagrange, 如果不适配 Lagrange 那请关闭此issue

**Comment by 2mf8** [comment]
好的，有空我会看看的

**Comment by 2mf8** [comment]
> https://github.com/2mf8/GoneBot/blob/2176fea2af8ac992663165f5750fcf1845168813/bot.go#L459-L460
> 
> 因为对接的 lagrange 的这个接口返回值字段为`resid` [lagrange文档](https://lagrangedev.github.io/Lagrange.Doc/Lagrange.OneBot/API/Extend/#%E6%9E%84%E9%80%A0%E5%90%88%E5%B9%B6%E8%BD%AC%E5%8F%91%E6%B6%88%E6%81%AF)
> 
> 所以`sfm.Data`会出现`nil.Data`的空指针问题
> 
> 我不知此项目是否全适配 Lagrange, 如果不适配 Lagrange 那请关闭此issue

已修复
![Screenshot_20240531_001349_com tencent mobileqq](https://github.com/2mf8/GoneBot/assets/28614037/879d86ad-180f-4fb1-9ad4-5b5d163645b0)
![Screenshot_20240531_001354_com tencent mobileqq](https://github.com/2mf8/GoneBot/assets/28614037/eab9d8c4-18ef-4de0-965d-f62b9f9af1c2)
![Screenshot_20240531_001402_com tencent mobileqq](https://github.com/2mf8/GoneBot/assets/28614037/5a4b6759-91d8-438f-b077-7b6d9df16b88)
![屏幕截图 2024-05-31 001328](https://github.com/2mf8/GoneBot/assets/28614037/da82200e-c2f6-4182-af3e-1f3e283a7c30)

**Comment by ycvk** [comment]
好的，麻烦了👌🏻
